/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const JobLazyImport = createFileRoute('/job')()
const FilamentLazyImport = createFileRoute('/filament')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const JobLazyRoute = JobLazyImport.update({
  path: '/job',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/job.lazy').then((d) => d.Route))

const FilamentLazyRoute = FilamentLazyImport.update({
  path: '/filament',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/filament.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/filament': {
      preLoaderRoute: typeof FilamentLazyImport
      parentRoute: typeof rootRoute
    }
    '/job': {
      preLoaderRoute: typeof JobLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  FilamentLazyRoute,
  JobLazyRoute,
])

/* prettier-ignore-end */
